### ISSUE TITLE
Statistiques

### ISSUE THREAD

**Issue by noelmace** [onestlatech/widget-engreve#5]
Lors du fork, j'ai purement et simplement enlevé le Google Analytics pour des raisons éthiques et de simplicité :
- https://github.com/noelmace/widget-engreve/commit/58ca88541552418b6aca3bae5936a8482e6c3374#diff-1fdf421c05c1140f6d71444ea2b27638L135-L178

Afin de permettre de compléter [le framaform](https://framaforms.org/onestlatech-appel-au-blocage-numerique-contre-le-projet-de-reforme-des-retraites-le-vendredi-24) lié à l'[appel à blocage](https://onestla.tech/publications/appel-action-24-janvier/), il pourrait être intéressant d'intégrer une alternative, telle que [matomo](https://matomo.org/), qui nous permettrait d'identifier les noms de domaine qui l'intègrent.

## TODO
- [ ] s'accorder sur la solution à employer (cf. [degooglisons-internet.fr](https://degooglisons-internet.org/fr/alternatives#ganalytics)) et la mettre en place
- [ ] identifier les problématiques d'isolation et de protection des données (iframe ? RGPD ?)
- [ ] alpha release et test
- [ ] release

**Comment by noelmace** [comment]
framaclic / dolomon ne fonctionne pas pour notre cas, étant donné qu'il ne peut donner le domaine visité à partir d'un même code de tracking.

**Comment by Ayst** [comment]
Effectivement ça serait une bonne idée pour connaitre automatiquement les sites utilisateurs.
Après ça pose aussi question, il faudrait bien informer l'utilisateur et offrir une possibilité de le désactiver.

**Comment by noelmace** [comment]
Pour la désactivation de GA, elle était prévue dés le départ :
https://github.com/noelmace/widget-engreve/commit/58ca88541552418b6aca3bae5936a8482e6c3374#diff-8dbf9328dd4ff71d8fc4212ce7ce59cfR33
On la remettrais en place bien entendu.

Le problème aujourd'hui serait surtout de trouver une solution alternative abordable. Matomon semble très bien, mais [trop cher](https://matomo.org/pricing/) tant qu'on ne dispose pas d'une infra où déployer notre propre instance.

Devrais-t-on faire une concession temporaire et utiliser GA entre temps ?

**Comment by esprit-libre** [comment]
Avec @cchaudier on se propose d'héberger sur notre Matomo. @noelmace je te créé un compte et tu me dis si ça te va ?

**Comment by noelmace** [comment]
thx @esprit-libre
Je vais tâcher de faire un POC prochainement, mais je manque de temps pour le projet ce mois-ci. Si je ne vais pas assez vite à votre goût, n'hésitez pas à démarrer une PR.

**Comment by noelmace** [comment]
Même si disposer de statistiques pourrait être intéressant pour évaluer l'ampleur de la mobilisation, mon expérience avec Matomo en l'abscence de tout traçage m'amène plutôt auourd'hui à conclure que les données qu'il nous permettrait de récolter seraient trop peu exploitable. Je ferme donc cette issue, mais n'hésitez pas à la réouvrir si quelqu'un souhaite reprendre le sujet.
