### ISSUE TITLE
Traduire CONTRIBUTING.md

### ISSUE THREAD

**Issue by noelmace** [onestlatech/widget-engreve#6]
Etant donné qu'il s'agit d'un projet où la (quasi) totalité des contributeurs et utilisateurs potentiels sont francophones, nous nous sommes accordés sur la règle suivante : 
- code (nom de variables, fonctions et commentaires) en anglais (par convention)
- documentation et discussions (issues et PR) en français (pour permettre compréhension et  contribution aux personnes ne disposant pas d'un niveau en anglais suffisant)

> Ceci est un projet de développeurs, pas l'académie française. Les anglicismes et termes techniques en anglais sont parfaitement admis, du moment que ça ne gène pas la compréhension :wink: Voir même quand ça l'améliore : par example, "Pull Request" (PR) ou "issue" sont préférés à "Fusiodemande" et "Rapport de problème".

La documentation contributeurs ([CONTRIBUTING.md](/CONTRIBUTING.md)) est cependant encore en anglais, et pourrait être traduire assez facilement.

## TODO

- [ ] renommer le fichier CONTRIBUER.md
- [ ] traduire, mettre à jour et corriger l'intégralité du texte
- [ ] ajouter une mention concernant la langue à employer suivant le contexte (cf. plus haut)

**Comment by noelmace** [comment]
Pour information, les description et certains nom de [labels](https://github.com/onestlatech/widget-engreve/issues/labels) ont également été traduits, mais pas tous, afin de suivre les conventions Github auxquelles les développeurs francophones sont habitués (par example : "good first issue" ou "wontfix").

**Comment by noelmace** [comment]
Résolut par 457adfc.
