### ISSUE TITLE
Ouvrir onestla.tech dans un nouvel onglet

### ISSUE THREAD

**Issue by noelmace** [onestlatech/widget-engreve#9]
@cchaudier a écrit dans #8 
> J'ai remarqué que sur la version bandeau de pied de page, le bouton "J'en suis. ->" ouvre le site reforme-retraite.info sur le même onglet.
Est-il possible d'avoir une variable qui permet d'avoir un comportement alternatif qui ouvre le site dans un nouvel onglet pour ne pas sortir le visiteur de nos site ?

Cette issue couvre uniquement la partie "ouvrir dans un nouvel onglet".

## TODO

- [ ] ajouter `target="_blank" rel="noopener noreferrer"` dans `setGlobalStrikeLinkUrl` :
https://github.com/onestlatech/widget-engreve/blob/master/src/index.js#L92-L95
- [ ] définir une nouvelle option pour permettre de rendre ce comportement paramétrable
- [ ] documenter dans README.md
